# Generated by Django 4.1 on 2022-11-14 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DetalleMantencion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("precio", models.IntegerField()),
                ("fecha", models.DateField()),
                ("kilometraje", models.IntegerField()),
                ("descripcion", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "verbose_name": "Detalle mantención",
                "verbose_name_plural": "Detalles mantenciones",
            },
        ),
        migrations.CreateModel(
            name="Mantencion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30)),
            ],
            options={
                "verbose_name": "Mantención",
                "verbose_name_plural": "Mantenciones",
            },
        ),
        migrations.CreateModel(
            name="Marca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30)),
            ],
            options={
                "verbose_name": "Marca",
                "verbose_name_plural": "Marcas",
            },
        ),
        migrations.CreateModel(
            name="Modelo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=20)),
                (
                    "marca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="vehiculos.marca",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modelo",
                "verbose_name_plural": "Modelos",
            },
        ),
        migrations.CreateModel(
            name="TipoVehiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name": "Tipo vehículo",
                "verbose_name_plural": "Tipos vehículos",
            },
        ),
        migrations.CreateModel(
            name="Vehiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("año", models.IntegerField()),
                (
                    "mantenciones",
                    models.ManyToManyField(
                        related_name="vehiculos",
                        through="vehiculos.DetalleMantencion",
                        to="vehiculos.mantencion",
                    ),
                ),
                (
                    "marca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="vehiculos.marca",
                    ),
                ),
                (
                    "modelo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="vehiculos.modelo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehículo",
                "verbose_name_plural": "Vehículos",
            },
        ),
        migrations.AddField(
            model_name="modelo",
            name="tipo_vehiculo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="vehiculos.tipovehiculo",
            ),
        ),
        migrations.AddField(
            model_name="detallemantencion",
            name="mantencion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="vehiculos.mantencion"
            ),
        ),
        migrations.AddField(
            model_name="detallemantencion",
            name="vehiculo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="vehiculos.vehiculo"
            ),
        ),
    ]
